### ISSUE TITLE
Determine BHNT 70 title

### ISSUE THREAD

**Issue by ligi** [berlin-hack-and-tell/org#1]
Idea - just answer with a suggestion and we take the suggestion with the most :+1:

**Comment by vog** [comment]
Show your april fools hacks

**Comment by lucasrangit** [comment]
"BHNT is Cancelled"

except it's not on April 1st, so people will really believe it's cancelled. :\

**Comment by ligi** [comment]
we already had april fools hacks: 2015-04-28-no34-april-fools-hacks

perhaps something around the falcon heavy start with successful landing of all 3 stages and the recovery of the nose cone

**Comment by lucasrangit** [comment]
I like space themes. What about...

Christopher Nolan--I mean--Einstein Was Right

**Comment by vog** [comment]
We also finally have fast multiplication, i.e. an algorithm that reaches the theoretical optimum:

* https://cp4space.wordpress.com/2019/03/28/complexity-of-integer-multiplication-almost-solved/

(This result has no practical relevance, though.)

However, both the falcon and the fast multiplication already happened at the end of March. Maybe we'll find some great news actually from April?

**Comment by stefanhoth** [comment]
I'm with @lucasrangit, themewise.

BHNT #70 - Black Hole & Tell

**Comment by ligi** [comment]
"Black Hole & Tell" - love it

**Comment by lucasrangit** [comment]
@stefanhoth , "Black Hole & Tell" is amazing.

**Comment by vog** [comment]
"Black Hole & Tell" is great!

BTW, is there any actual news about black holes in March/April that I was missing?

**Comment by ligi** [comment]
yay - seems we have rough consensus around Black Hole & Tell

this is the corresponding news item: https://www.youtube.com/watch?v=S_GVbuddri8

> The Event Horizon Telescope Collaboration observed the supermassive black hole at the center of M87, finding the dark central shadow in accordance with General Relativity, further demonstrating the power of this 100 year-old theory.

**Comment by ligi** [comment]
meetup under this title is announced: https://www.meetup.com/de-DE/Berlin-Hack-and-Tell/events/260731561
