### ISSUE TITLE
BHNT #73 title and news

### ISSUE THREAD

**Issue by MarlonSchultz** [berlin-hack-and-tell/org#10]
The next BHNT is coming up and we are once again in need of a title and news.

### TITLE

I am blank.

### NEWS

- Galileo positioning system broke down
- Alan Turing will be printed upon the next 50 pounds bill (https://www.heise.de/newsticker/meldung/Alan-Turings-Portraet-kommt-auf-die-britische-50-Pfund-Banknote-4471518.html - german)

**Comment by ligi** [comment]
title suggestion - "libre not libra"
I would actually love to have this title. I just see 2 problems: a) perhaps it is too blockchain focused b) libira is news from end of june and not july
I think it could have been announced shortly before the last BHNT
would still love to use this title - but can also understand if you don't

**Comment by ligi** [comment]
let's also add the libera news to the news section. Just saw in the slides from last month it was not mentioned. Would also love to play this clip then: https://twitter.com/RealBankReform/status/1151541426179756032

also suggestion as a news item:
someone was wearing an awesome shirt:
https://twitter.com/mr_ligi/status/1151656568762638336

**Comment by ligi** [comment]
just created the meetup under the name "libre - not libra"

**Comment by MarlonSchultz** [comment]
Can we add "Like tears in rain" to the news section - or even call the next BHNT this way? Its referencing the recent passing of Rudger Hauer.

Huge Blade Runner fan here. :D

**Comment by ligi** [comment]
for calling it this way it is too late now as the meetup is already announced and only 2 days in the future. But will add it as a news-item.

**Comment by MarlonSchultz** [comment]
I didnt mean #73. But news is good for me. Thx. :D

**Comment by vog** [comment]
I love this Blade Runner reference. Would be great for BHNT #74+.

By the way, there is a great "nerdy" variant of the Blade Runner theme song, namely, the [official song of OpenBSD 5.3: "Blade Swimmer"](https://www.openbsd.org/lyrics.html#53)

>  I've seen things your programs wouldn't believe.
> 
> [laughs]
> 
> Stack frames unwinding with Turing complete behaviour.
> 
> I watched threads racing trampoline bindings in ld.so.
> 
> All those overwrites will be lost in memory
> like [coughs] accesses to NULL.
> 
> Time to dump core.
