### ISSUE TITLE
BHNT 77 Hacking 2020

### ISSUE THREAD

**Issue by lucasrangit** [berlin-hack-and-tell/org#12]
- [x] Title
- [x] Announce
- [x] News
- [x] Slides

**Comment by vog** [comment]
News: On 2019-Dec-26 06:01:41 UTC the 27th round of the IOCCC started. Deadline for submissions: 2020-Mar-15 06:26:49 UTC. See https://ioccc.org/

**Comment by vog** [comment]
Idea for title: First hacks in the golden 20s

**Comment by vog** [comment]
News (perhaps):

Interview with Theo De Raadt (security freak and leader of OpenBSD):

* Announcement: http://www.undeadly.org/cgi?action=article;sid=20191231214356
* Video: http://thebrotherswisp.com/index.php/tom-interviews-theo-de-raadt-of-the-openbsd-project/

**Comment by vog** [comment]
* Rust 1.40.0 released! https://blog.rust-lang.org/2019/12/19/Rust-1.40.0.html

**Comment by lucasrangit** [comment]
Thanks for picking a title and sending the announcements @ligi !

**Comment by ligi** [comment]
yea - just noticed today there is only one week to go. And sorry to not pick @vog 's title - but it was a bit long.
Hope to see ya'll next Tuesday!

**Comment by lucasrangit** [comment]
No I like your title, because it also refers to "hacking the 2020 US elections" :astonished:

**Comment by lucasrangit** [comment]
News:
* https://www.losinglena.com/ Help us remove one image to make millions of women feel welcome in tech.

**Comment by ligi** [comment]
news:
 - 36c3 
- nym launch (e.g. via https://twitter.com/nymproject/status/1210869616169369601)
- and https://twitter.com/nymproject/status/1219957266998317056 can be transition to new year
 - new year with drones (e.g. via https://twitter.com/nytimes/status/1212156518193340416)
 - Picard 1st episode (e.g. via https://twitter.com/DoctorLongscarf/status/1220527961142693888) 
 - parity -> DAO (e.g. via https://twitter.com/nymproject/status/1210869616169369601)
- Specification for specification for Blockchain IDs: e.g. via https://twitter.com/ChainStandards/status/1219267199589896192 
- in3 relese: https://twitter.com/wallethapp/status/1215293301269635072

**Comment by lucasrangit** [comment]
@ligi the "parity -> DAO (e.g. via https://twitter.com/nymproject/status/1210869616169369601)" has the wrong URL.

**Comment by ligi** [comment]
true - sorry - copy and paste error when collecting the links - here the correct link: https://www.parity.io/parity-ethereum-openethereum-dao/

**Comment by lucasrangit** [comment]
Slides: https://berlinhackandtell.rocks/slides/2020-01-28-no77-hacking-2020#/

@ligi

**Comment by ligi** [comment]
Thanks. LGTM
perhaps just make the 36c3 slide a bit more colorful like with this: https://twitter.com/maltman23/status/1217739131318497280

you are around tonight right?

**Comment by lucasrangit** [comment]
Sure, good idea. I'm on my way now.

**Comment by ligi** [comment]
Thanks for the slides and the other support @lucasrangit !
can you make a PR for the slides - will merge them then
closing BHNT 77
