### ISSUE TITLE
BHNT 78

### ISSUE THREAD

**Issue by lucasrangit** [berlin-hack-and-tell/org#13]

**Comment by lucasrangit** [comment]
News
Linus merges wireguard into kernel 5.6 https://github.com/torvalds/linux/commit/bd2463ac7d7ec51d432f23bf0e893fb371a908cd

**Comment by ligi** [comment]
Title suggestion: "Flash your hacks"
 - bit of a hint to this very recent hack https://twitter.com/kermankohli/status/1229653115470667777

**Comment by lucasrangit** [comment]
How about a Brexit related title?

**Comment by vog** [comment]
Brexit related:

* Haxit
* Hacksit
* Hackzit

**Comment by ligi** [comment]
great ideas - but unfortunately too late - wanted to announce a week before the event and so did it yesterday ..

**Comment by vog** [comment]
Thinking more of it, maybe it's indeed better to not remind the audience of that tragedy. It would have been a bit harsh towards the first presenter if we pull down the audience like that.

**Comment by ligi** [comment]
slides PR: https://github.com/berlin-hack-and-tell/berlinhackandtell.rocks/pull/282
could use some more news
