### ISSUE TITLE
Create BHNT 70 slides

### ISSUE THREAD

**Issue by ligi** [berlin-hack-and-tell/org#3]

**Comment by lucasrangit** [comment]
some news:
* https://www.jpl.nasa.gov/edu/news/2019/4/19/how-scientists-captured-the-first-image-of-a-black-hole/
* https://www.zdnet.com/article/popular-jquery-javascript-library-impacted-by-prototype-pollution-flaw/

**Comment by MarlonSchultz** [comment]
some sidenews:

- the gameboy is heading for midlife crisis with 30 years of age now
- [Chelsea Manning is again and still in prison for not testifying in a case against wikileaks](https://www.politico.com/f/?id=0000016a-4509-d50f-a96a-ed5b99cc0001)
- Julian Assange had to leave the ecuadorian embassy
- relentless DoppelGanger - an AI plays deathmetal 24/7 (https://www.youtube.com/watch?v=CNNmBtNcccE)

things to consider:
- 23th till 26th of may are elections in the EU

And so on and so forth - so many things happend. SpaceX had an explosion, a bunch of new library versions came out.

**Comment by MarlonSchultz** [comment]
I can create the slides on monday and open a PR.

**Comment by ligi** [comment]
yay - thanks!

**Comment by lucasrangit** [comment]
Done and merged in https://github.com/berlin-hack-and-tell/berlinhackandtell.rocks/pull/247

**Comment by lucasrangit** [comment]
@ligi re-opened? what's missing?

**Comment by ligi** [comment]
I think the date is wrong:

today is the 30th and not the 29th:

create mode 100644 _slides/2019-04-29-no70-black-hole-and-tell.md

and what do you think about adding: 
https://twitter.com/mr_ligi/status/1122808812950491137

I think this was the best talk this month

**Comment by MarlonSchultz** [comment]
And i forgot to add the EU elections, ill add them on the fly later at the base. Will be there around 1820.

**Comment by lucasrangit** [comment]
Since I had the file open I fixed the date and added the talk. Thanks @ligi .

No more changes from me @MarlonSchultz .
