### ISSUE TITLE
c-base calendar change

### ISSUE THREAD

**Issue by ligi** [berlin-hack-and-tell/org#4]
in meetup we now have 19:00 - but still states 18:30 - we should syncronize this (had users confused already) 

I would vote for 19:00 - what do you think?

**Comment by MarlonSchultz** [comment]
Im fine with either of both times. I guess there are reason for and against a later start.

However, I do think that the later we start, _we might be_ able to prepare things better beforehand.

**Comment by lucasrangit** [comment]
19:00 is better and what I always thought it was.

Since it's after work and people should get dinner before I think a 19:15 ish start gives people time to come prepared to demo.

**Comment by stefanhoth** [comment]
I'm happy with whatever you decide. 

H&T always started around 7pm, that's true.
The reason why 6.30pm is in the c-base calendar was to assure the mainhall is blocked from at least that time on. That gives enough room to set up everything, even when a midday event happened.

I didn't hear any complaints about that difference as people are usually chilled to come in, have a drink and chat. But I might just have talked to the wrong people.

**Comment by ligi** [comment]
I had 1-2 people telling me they where confused about the different starts at meetup and the calendar

**Comment by MarlonSchultz** [comment]
Starting times have been fixed.
