### ISSUE TITLE
Technical Stuff / Communication / Stuff

### ISSUE THREAD

**Issue by MarlonSchultz** [berlin-hack-and-tell/org#8]
Since we had a bunch of technical issues last time, i would like to try to get a tour by cascha about the sound setup. Who else would like to have an intro about the sound setup?

Furthermore I will bring a small switch the next time, if the mate-light switch is borken again.

Aaaand last one: Is it a good idea, to establish some kind of chat-liek communication? I dont care if  its IRC, discord or whatever. I think a fast way of deciding things would be great.

**Comment by ligi** [comment]
opened a room on [matrix] https://riot.im/app/#/room/#bhnt:matrix.org

**Comment by vog** [comment]
I receive the following error message: "You are not invited to this room."

**Comment by ligi** [comment]
sorry should work now - thought public is default but it is invite only now - changed to public

**Comment by MarlonSchultz** [comment]
Riot works for me. I am registered and in the room.
