### ISSUE TITLE
BHNT 73-1 Announcement && Title && Slides

### ISSUE THREAD

**Issue by MarlonSchultz** [berlin-hack-and-tell/org#9]
### Social marketing stuff
Since Ligi is on vacation - who can announce the next BHNT on meetup and twitter?

### Title

I am really lost here.

### slide news

- E-Scooters are coming to Berlin
- github acquires pull panda
- new istio release plan (is that even news?)
- your stuff

### who will be there ?

I will be there and can present. I am happy for anyone else to help out.

**Comment by lucasrangit** [comment]
Title : "BHNT #72 - Off By One". Reference to last one which was actually off by one.

News
* Linux kernel panic tcp trigger https://github.com/Netflix/security-bulletins/blob/master/advisories/third-party/2019-001.md#title-linux-and-freebsd-kernel-multiple-tcp-based-remote-denial-of-service-vulnerabilities

**Comment by MarlonSchultz** [comment]
Can you create stuff on the meetup page? 

I like the title. :)

**Comment by lucasrangit** [comment]
No I don't have permissions.

@stefanhoth can though.

**Comment by lucasrangit** [comment]
More news:

* JPL hacked via rogue Raspberry Pi https://threatpost.com/feds-hackers-mission-control-data-nasa-jpl/145842/

**Comment by stefanhoth** [comment]
I've created a draft here https://www.meetup.com/Berlin-Hack-and-Tell/events/drafts/

And I made @lucasrangit and @MarlonSchultz both organisers so you should be able to publish it. Please confirm :-)

**Comment by vog** [comment]
Please note that "Off by One" is already taken, from BHNT#57:

* https://berlinhackandtell.rocks/2018-01-30-no57-off-by-one

Back then, we also had an actual off-by-one error in counting.

I remember vaguely that we already discussed this a month ago, or so ... but maybe I just thought it and forgot to write it to you.

If you still want to stick to that title, I propose to at least "nerdify" it, so it is different from the original, e.g.

* Off by 0x01
* Off by 2^3
* Off by (2 xor 3)
* Off by 2⊻3 (using the official XOR symbol "⊻" = U+22BB)
* Off by 2 (i.e. an off-by-one error in the title as well)

**Comment by vog** [comment]
Regarding the news:

IOCCC 2019 finished! (this happened in May, but didn't appear the last month's slides, if I remember correctly):

* https://mobile.twitter.com/ioccc/status/1127747710008717312
* http://www.ioccc.org/2019/whowon.html

Two winning entries from Germany, both by ... you know.

Alas, the winning entries themselves (the code and the hints and the spoilers) are not yet published, and won't be before July. So maybe it  makes more sense to mention this next month? You decide.

**Comment by MarlonSchultz** [comment]
The event has been announce, no nerdy title tho. :)

**Comment by lucasrangit** [comment]
"Off by 2" would be hilarious.

**Comment by MarlonSchultz** [comment]
I will create the slides this afternoon.
